# Generated by Django 4.2.6 on 2023-11-03 07:38

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_alter_profile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(blank=True, default='static/authentication/images/default-profile.jpg', null=True, upload_to='authentication/images/', validators=[django.core.validators.FileExtensionValidator(['jpg', 'jpeg', 'gif', 'png'])]),
        ),
    ]
