# Generated by Django 4.2.6 on 2023-11-03 09:16

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(blank=True, default='images/profiles/default-profile.jpg', null=True, upload_to='images/profiles/', validators=[django.core.validators.FileExtensionValidator(['jpg', 'jpeg', 'gif', 'png'])]),
        ),
    ]
